### ISSUE TITLE
Explain imsc in the README

### ISSUE THREAD

**Issue by jwhitlock** [mdn/imsc#9]
The README uses IMSC without explaining what it is:

* [ ] Independent Mystery Shoppers Coalition
* [ ] Institute of Mathematical Sciences
* [ ] Information Management Steering Committee
* [ ] Installation Mission Support Center (US DoD)
* [ ] Independent Model Space Control (NASA)
* [ ] Something else?

The README should spell out the term before abbreviating it.

**Comment by palemieux** [comment]
IMSC = [TTML Profiles for Internet Media Subtitles and Captions](https://www.w3.org/TR/ttml-imsc1.1/)

See #10
